[build]
aptPackages = [
  "libglib2.0-0",
  "libnss3",
  "libatk1.0-0",
  "libatk-bridge2.0-0",
  "libx11-6",
  "libxcomposite1",
  "libxdamage1",
  "libxext6",
  "libxfixes3",
  "libxrandr2",
  "libgbm1",
  "libasound2",
  "libpangocairo-1.0-0",
  "libpango-1.0-0",
  "libcairo2",
  "libxkbcommon0",
  "libgtk-3-0",
  "libdrm2"
]
